---
- name: Ensure the HTML directory exists
      become: true
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'
- name: Ensure unzip is installed
  become: true
  ansible.builtin.apt:
    name: unzip
    state: present
- name: Get Lighthouse distrib
  ansible.builtin.get_url:
    url: "https://github.com/GoogleChrome/lighthouse/archive/refs/tags/v{{ lighthouse_version }}.zip"
    dest: /tmp/lighthouse.zip
    mode: "0644"
- name: Unzip distrib archive
  become: true
  ansible.builtin.unarchive:
    src: /tmp/lighthouse.zip
    dest: /var/www/html/
    remote_src: true
- name: Nginx | Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
  notify: Start nginx
- name: Nginx | Create config
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload nginx
